POST http://localhost:8080/feed/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6eyJzdGF0dXMiOiJJIGFtIG5ldyIsInBvc3RzIjpbXSwiX2lkIjoiNWUwN2EzOGNhY2Y5MDExZGFkMmRlZmUyIiwiZW1haWwiOiJmZWxpcGUuamFuc2VuQG91dGxvb2suY29tIiwicGFzc3dvcmQiOiIkMmEkMTIkYUFsRURDTTZ5QktDbEdlNXZaaklRdVIvcWZaelpYZFZBajMuNEhWVW9pWVFWcDJ0MFdMTDYiLCJuYW1lIjoiRmVsaXBlIEphbnNlbiIsIl9fdiI6MH0sInVzZXJJZCI6IjVlMDdhMzhjYWNmOTAxMWRhZDJkZWZlMiIsImlhdCI6MTU3NzU1ODk1OSwiZXhwIjoxNTc3NTYyNTU5fQ.dfUGx0U5UvVz60Cd8eQm6Gnv57iJSCWgkV3CA8UCyVc

{
  "title": "last page",
  "imageUrl" : null,
  "content" : "12345dsadsa"
}

###

GET http://localhost:8080/feed/posts?page=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6eyJzdGF0dXMiOiJJIGFtIG5ldyIsInBvc3RzIjpbXSwiX2lkIjoiNWUwN2EzOGNhY2Y5MDExZGFkMmRlZmUyIiwiZW1haWwiOiJmZWxpcGUuamFuc2VuQG91dGxvb2suY29tIiwicGFzc3dvcmQiOiIkMmEkMTIkYUFsRURDTTZ5QktDbEdlNXZaaklRdVIvcWZaelpYZFZBajMuNEhWVW9pWVFWcDJ0MFdMTDYiLCJuYW1lIjoiRmVsaXBlIEphbnNlbiIsIl9fdiI6MH0sInVzZXJJZCI6IjVlMDdhMzhjYWNmOTAxMWRhZDJkZWZlMiIsImlhdCI6MTU3NzU1ODk1OSwiZXhwIjoxNTc3NTYyNTU5fQ.dfUGx0U5UvVz60Cd8eQm6Gnv57iJSCWgkV3CA8UCyVc

###

GET http://localhost:8080/feed/post/5e063f09c8cfb71daa545928
Content-Type: application/json

###

PUT http://localhost:8080/feed/post/5e07972fedd06419a292c7f8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6eyJzdGF0dXMiOiJJIGFtIG5ldyIsInBvc3RzIjpbXSwiX2lkIjoiNWUwNzlhMDBhMmIwODcxYjEyNzY3N2RmIiwiZW1haWwiOiJmZWxpcGVqYW5zZW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTIkVGRLdHFqRjg2ZEx6V3VORXZ0UzJpZWo3RmQ3b2xFSVNUUEU0ZS5seDRVYmJ3anhmWnlJaFMiLCJuYW1lIjoiRmVsaXBlIEphbnNlbiIsIl9fdiI6MH0sInVzZXJJZCI6IjVlMDc5YTAwYTJiMDg3MWIxMjc2NzdkZiIsImlhdCI6MTU3NzU1NjYzOCwiZXhwIjoxNTc3NTYwMjM4fQ.WHOCCCaNpL7xgtrNZI5a9VVfXv37YKJjmDmL24gS-6w

{
  "title": "Post Edited",
  "imageUrl" : null,
  "content" : "content post"
}

###

DELETE http://localhost:8080/feed/post/5e07a3c4acf9011dad2defe3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6eyJzdGF0dXMiOiJJIGFtIG5ldyIsInBvc3RzIjpbXSwiX2lkIjoiNWUwN2EzOGNhY2Y5MDExZGFkMmRlZmUyIiwiZW1haWwiOiJmZWxpcGUuamFuc2VuQG91dGxvb2suY29tIiwicGFzc3dvcmQiOiIkMmEkMTIkYUFsRURDTTZ5QktDbEdlNXZaaklRdVIvcWZaelpYZFZBajMuNEhWVW9pWVFWcDJ0MFdMTDYiLCJuYW1lIjoiRmVsaXBlIEphbnNlbiIsIl9fdiI6MH0sInVzZXJJZCI6IjVlMDdhMzhjYWNmOTAxMWRhZDJkZWZlMiIsImlhdCI6MTU3NzU1ODk1OSwiZXhwIjoxNTc3NTYyNTU5fQ.dfUGx0U5UvVz60Cd8eQm6Gnv57iJSCWgkV3CA8UCyVc

###
